source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
pod 'SDWebImage'
pod 'Alamofire'
pod 'NVActivityIndicatorView'
pod 'MMDrawerController'
pod 'SwiftyJSON'
pod 'SnapKit'
